// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: transaction/Transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionID string `protobuf:"bytes,1,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
}

func (x *TranxReq) Reset() {
	*x = TranxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_Transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranxReq) ProtoMessage() {}

func (x *TranxReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_Transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranxReq.ProtoReflect.Descriptor instead.
func (*TranxReq) Descriptor() ([]byte, []int) {
	return file_transaction_Transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TranxReq) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

type TranxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TranxOutput string `protobuf:"bytes,1,opt,name=TranxOutput,proto3" json:"TranxOutput,omitempty"`
}

func (x *TranxRes) Reset() {
	*x = TranxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_Transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranxRes) ProtoMessage() {}

func (x *TranxRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_Transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranxRes.ProtoReflect.Descriptor instead.
func (*TranxRes) Descriptor() ([]byte, []int) {
	return file_transaction_Transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TranxRes) GetTranxOutput() string {
	if x != nil {
		return x.TranxOutput
	}
	return ""
}

type DepoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionID string `protobuf:"bytes,1,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	Amount        string `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *DepoReq) Reset() {
	*x = DepoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_Transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepoReq) ProtoMessage() {}

func (x *DepoReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_Transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepoReq.ProtoReflect.Descriptor instead.
func (*DepoReq) Descriptor() ([]byte, []int) {
	return file_transaction_Transaction_proto_rawDescGZIP(), []int{2}
}

func (x *DepoReq) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *DepoReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type DepoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepoOutput string `protobuf:"bytes,1,opt,name=DepoOutput,proto3" json:"DepoOutput,omitempty"`
}

func (x *DepoRes) Reset() {
	*x = DepoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_Transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepoRes) ProtoMessage() {}

func (x *DepoRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_Transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepoRes.ProtoReflect.Descriptor instead.
func (*DepoRes) Descriptor() ([]byte, []int) {
	return file_transaction_Transaction_proto_rawDescGZIP(), []int{3}
}

func (x *DepoRes) GetDepoOutput() string {
	if x != nil {
		return x.DepoOutput
	}
	return ""
}

var File_transaction_Transaction_proto protoreflect.FileDescriptor

var file_transaction_Transaction_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x6e, 0x78, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x2c,
	0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x78, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72,
	0x61, 0x6e, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x54, 0x72, 0x61, 0x6e, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x47, 0x0a, 0x07,
	0x44, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6f, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x70, 0x6f, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x32, 0x8b, 0x01, 0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x15,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x78, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44,
	0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_Transaction_proto_rawDescOnce sync.Once
	file_transaction_Transaction_proto_rawDescData = file_transaction_Transaction_proto_rawDesc
)

func file_transaction_Transaction_proto_rawDescGZIP() []byte {
	file_transaction_Transaction_proto_rawDescOnce.Do(func() {
		file_transaction_Transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_Transaction_proto_rawDescData)
	})
	return file_transaction_Transaction_proto_rawDescData
}

var file_transaction_Transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_Transaction_proto_goTypes = []interface{}{
	(*TranxReq)(nil), // 0: transaction.TranxReq
	(*TranxRes)(nil), // 1: transaction.TranxRes
	(*DepoReq)(nil),  // 2: transaction.DepoReq
	(*DepoRes)(nil),  // 3: transaction.DepoRes
}
var file_transaction_Transaction_proto_depIdxs = []int32{
	0, // 0: transaction.bankService.GetBalance:input_type -> transaction.TranxReq
	2, // 1: transaction.bankService.DepositeAmount:input_type -> transaction.DepoReq
	1, // 2: transaction.bankService.GetBalance:output_type -> transaction.TranxRes
	3, // 3: transaction.bankService.DepositeAmount:output_type -> transaction.DepoRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_Transaction_proto_init() }
func file_transaction_Transaction_proto_init() {
	if File_transaction_Transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_Transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_Transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_Transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_Transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_Transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_Transaction_proto_goTypes,
		DependencyIndexes: file_transaction_Transaction_proto_depIdxs,
		MessageInfos:      file_transaction_Transaction_proto_msgTypes,
	}.Build()
	File_transaction_Transaction_proto = out.File
	file_transaction_Transaction_proto_rawDesc = nil
	file_transaction_Transaction_proto_goTypes = nil
	file_transaction_Transaction_proto_depIdxs = nil
}
